"""Claim: a claim raised against a Policy for a covered benefit (Stage 14).

A claim is scoped to a specific ``Member`` enrolled under a ``Policy`` and
records the business event that triggered it. Claims move through a small
decision-and-payout lifecycle:

    submitted -> approved -> paid
            \\-> rejected        (rejected is terminal)

``amount_approved`` is set when an underwriter approves a claim; it carries
forward to ``paid``. A claim may target a specific elected benefit, but the
member and policy are always required.

The claim is validated at submission time (see ``services/claims``): the
incident date must fall within the policy's active term and the member must be
active. ``claim_number`` is generated by the service layer.
"""
import datetime as dt

from sqlalchemy import Date, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Claim(Base):
    __tablename__ = "claims"

    id: Mapped[int] = mapped_column(primary_key=True)
    claim_number: Mapped[str] = mapped_column(String(60), unique=True, index=True)
    policy_id: Mapped[int] = mapped_column(ForeignKey("policies.id"))
    member_id: Mapped[int] = mapped_column(ForeignKey("members.id"))
    benefit_id: Mapped[int | None] = mapped_column(
        ForeignKey("benefits.id"), nullable=True
    )
    # "submitted" | "approved" | "rejected" | "paid"
    status: Mapped[str] = mapped_column(String(20), default="submitted")
    incident_date: Mapped[dt.date] = mapped_column(Date)
    amount_claimed: Mapped[float] = mapped_column(Numeric(12, 2))
    # Set on approval; nullable until an underwriter adjudicates.
    amount_approved: Mapped[float | None] = mapped_column(
        Numeric(12, 2), nullable=True
    )
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: dt.datetime.now(dt.timezone.utc)
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: dt.datetime.now(dt.timezone.utc),
        onupdate=lambda: dt.datetime.now(dt.timezone.utc),
    )

    policy: Mapped["Policy"] = relationship("Policy")
    member: Mapped["Member"] = relationship("Member")
    benefit: Mapped["Benefit | None"] = relationship("Benefit")
