spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/group_insure
    username: group_insure
    password: group_insure
  jpa:
    h2ddl-auto: update
    properties:
      hibernate:
        format_sql: true
